### ISSUE TITLE
bytes feature is missing?

### ISSUE THREAD

**Issue by Xudong-Huang** [botika/buf-min#15]
now we report the trait `yarte::Buffer` is not implemented for `bytes::bytes_mut::BytesMut` when using yarte

**Comment by zzau13** [comment]
https://github.com/botika/yarte/tree/master/examples/bytes 

I add an example with this case. i.e. add in `Cargo.toml` as dependency
```toml
buf-min = { version = "0.7", features = ["bytes"] }
```
